# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('core', '0003_portfoliopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.wagtailcore.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('rich_text', wagtail.wagtailcore.blocks.RichTextBlock(icon='doc-full', label='Rich Text')), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock(icon='site', label='Raw HTML')))),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post date'),
        ),
    ]
